// lib/countryCodes.ts
export const countryCodes = [
    { code: '+93', flag: '🇦🇫', country: 'Afghanistan' },
    { code: '+355', flag: '🇦🇱', country: 'Albania' },
    { code: '+213', flag: '🇩🇿', country: 'Algeria' },
    { code: '+376', flag: '🇦🇩', country: 'Andorra' },
    { code: '+244', flag: '🇦🇴', country: 'Angola' },
    { code: '+1-268', flag: '🇦🇬', country: 'Antigua and Barbuda' },
    { code: '+54', flag: '🇦🇷', country: 'Argentina' },
    { code: '+374', flag: '🇦🇲', country: 'Armenia' },
    { code: '+61', flag: '🇦🇺', country: 'Australia' },
    { code: '+43', flag: '🇦🇹', country: 'Austria' },
    { code: '+994', flag: '🇦🇿', country: 'Azerbaijan' },
    { code: '+1-242', flag: '🇧🇸', country: 'Bahamas' },
    { code: '+973', flag: '🇧🇭', country: 'Bahrain' },
    { code: '+880', flag: '🇧🇩', country: 'Bangladesh' },
    { code: '+1-246', flag: '🇧🇧', country: 'Barbados' },
    { code: '+375', flag: '🇧🇾', country: 'Belarus' },
    { code: '+32', flag: '🇧🇪', country: 'Belgium' },
    { code: '+501', flag: '🇧🇿', country: 'Belize' },
    { code: '+229', flag: '🇧🇯', country: 'Benin' },
    { code: '+975', flag: '🇧🇹', country: 'Bhutan' },
    { code: '+591', flag: '🇧🇴', country: 'Bolivia' },
    { code: '+387', flag: '🇧🇦', country: 'Bosnia and Herzegovina' },
    { code: '+267', flag: '🇧🇼', country: 'Botswana' },
    { code: '+55', flag: '🇧🇷', country: 'Brazil' },
    { code: '+673', flag: '🇧🇳', country: 'Brunei' },
    { code: '+359', flag: '🇧🇬', country: 'Bulgaria' },
    { code: '+226', flag: '🇧🇫', country: 'Burkina Faso' },
    { code: '+257', flag: '🇧🇮', country: 'Burundi' },
    { code: '+855', flag: '🇰🇭', country: 'Cambodia' },
    { code: '+237', flag: '🇨🇲', country: 'Cameroon' },
    { code: '+1', flag: '🇨🇦', country: 'Canada' },
    { code: '+238', flag: '🇨🇻', country: 'Cape Verde' },
    { code: '+236', flag: '🇨🇫', country: 'Central African Republic' },
    { code: '+235', flag: '🇹🇩', country: 'Chad' },
    { code: '+56', flag: '🇨🇱', country: 'Chile' },
    { code: '+86', flag: '🇨🇳', country: 'China' },
    { code: '+57', flag: '🇨🇴', country: 'Colombia' },
    { code: '+269', flag: '🇰🇲', country: 'Comoros' },
    { code: '+242', flag: '🇨🇬', country: 'Congo' },
    { code: '+243', flag: '🇨🇩', country: 'Congo, Democratic Republic' },
    { code: '+506', flag: '🇨🇷', country: 'Costa Rica' },
    { code: '+385', flag: '🇭🇷', country: 'Croatia' },
    { code: '+53', flag: '🇨🇺', country: 'Cuba' },
    { code: '+357', flag: '🇨🇾', country: 'Cyprus' },
    { code: '+420', flag: '🇨🇿', country: 'Czech Republic' },
    { code: '+45', flag: '🇩🇰', country: 'Denmark' },
    { code: '+253', flag: '🇩🇯', country: 'Djibouti' },
    { code: '+1-767', flag: '🇩🇲', country: 'Dominica' },
    { code: '+1-809', flag: '🇩🇴', country: 'Dominican Republic' },
    { code: '+593', flag: '🇪🇨', country: 'Ecuador' },
    { code: '+20', flag: '🇪🇬', country: 'Egypt' },
    { code: '+503', flag: '🇸🇻', country: 'El Salvador' },
    { code: '+240', flag: '🇬🇶', country: 'Equatorial Guinea' },
    { code: '+291', flag: '🇪🇷', country: 'Eritrea' },
    { code: '+372', flag: '🇪🇪', country: 'Estonia' },
    { code: '+251', flag: '🇪🇹', country: 'Ethiopia' },
    { code: '+679', flag: '🇫🇯', country: 'Fiji' },
    { code: '+358', flag: '🇫🇮', country: 'Finland' },
    { code: '+33', flag: '🇫🇷', country: 'France' },
    { code: '+241', flag: '🇬🇦', country: 'Gabon' },
    { code: '+220', flag: '🇬🇲', country: 'Gambia' },
    { code: '+995', flag: '🇬🇪', country: 'Georgia' },
    { code: '+49', flag: '🇩🇪', country: 'Germany' },
    { code: '+233', flag: '🇬🇭', country: 'Ghana' },
    { code: '+30', flag: '🇬🇷', country: 'Greece' },
    { code: '+1-473', flag: '🇬🇩', country: 'Grenada' },
    { code: '+502', flag: '🇬🇹', country: 'Guatemala' },
    { code: '+224', flag: '🇬🇳', country: 'Guinea' },
    { code: '+245', flag: '🇬🇼', country: 'Guinea-Bissau' },
    { code: '+592', flag: '🇬🇾', country: 'Guyana' },
    { code: '+509', flag: '🇭🇹', country: 'Haiti' },
    { code: '+504', flag: '🇭🇳', country: 'Honduras' },
    { code: '+36', flag: '🇭🇺', country: 'Hungary' },
    { code: '+354', flag: '🇮🇸', country: 'Iceland' },
    { code: '+91', flag: '🇮🇳', country: 'India' },
    { code: '+62', flag: '🇮🇩', country: 'Indonesia' },
    { code: '+98', flag: '🇮🇷', country: 'Iran' },
    { code: '+964', flag: '🇮🇶', country: 'Iraq' },
    { code: '+353', flag: '🇮🇪', country: 'Ireland' },
    { code: '+972', flag: '🇮🇱', country: 'Israel' },
    { code: '+39', flag: '🇮🇹', country: 'Italy' },
    { code: '+1-876', flag: '🇯🇲', country: 'Jamaica' },
    { code: '+81', flag: '🇯🇵', country: 'Japan' },
    { code: '+962', flag: '🇯🇴', country: 'Jordan' },
    { code: '+7', flag: '🇰🇿', country: 'Kazakhstan' },
    { code: '+254', flag: '🇰🇪', country: 'Kenya' },
    { code: '+686', flag: '🇰🇮', country: 'Kiribati' },
    { code: '+965', flag: '🇰🇼', country: 'Kuwait' },
    { code: '+996', flag: '🇰🇬', country: 'Kyrgyzstan' },
    { code: '+856', flag: '🇱🇦', country: 'Laos' },
    { code: '+371', flag: '🇱🇻', country: 'Latvia' },
    { code: '+961', flag: '🇱🇧', country: 'Lebanon' },
    { code: '+266', flag: '🇱🇸', country: 'Lesotho' },
    { code: '+231', flag: '🇱🇷', country: 'Liberia' },
    { code: '+218', flag: '🇱🇾', country: 'Libya' },
    { code: '+423', flag: '🇱🇮', country: 'Liechtenstein' },
    { code: '+370', flag: '🇱🇹', country: 'Lithuania' },
    { code: '+352', flag: '🇱🇺', country: 'Luxembourg' },
    { code: '+261', flag: '🇲🇬', country: 'Madagascar' },
    { code: '+265', flag: '🇲🇼', country: 'Malawi' },
    { code: '+60', flag: '🇲🇾', country: 'Malaysia' },
    { code: '+960', flag: '🇲🇻', country: 'Maldives' },
    { code: '+223', flag: '🇲🇱', country: 'Mali' },
    { code: '+356', flag: '🇲🇹', country: 'Malta' },
    { code: '+692', flag: '🇲🇭', country: 'Marshall Islands' },
    { code: '+222', flag: '🇲🇷', country: 'Mauritania' },
    { code: '+230', flag: '🇲🇺', country: 'Mauritius' },
    { code: '+52', flag: '🇲🇽', country: 'Mexico' },
    { code: '+691', flag: '🇫🇲', country: 'Micronesia' },
    { code: '+373', flag: '🇲🇩', country: 'Moldova' },
    { code: '+377', flag: '🇲🇨', country: 'Monaco' },
    { code: '+976', flag: '🇲🇳', country: 'Mongolia' },
    { code: '+382', flag: '🇲🇪', country: 'Montenegro' },
    { code: '+212', flag: '🇲🇦', country: 'Morocco' },
    { code: '+258', flag: '🇲🇿', country: 'Mozambique' },
    { code: '+95', flag: '🇲🇲', country: 'Myanmar' },
    { code: '+977', flag: '🇳🇵', country: 'Nepal' },
    { code: '+31', flag: '🇳🇱', country: 'Netherlands' },
    { code: '+64', flag: '🇳🇿', country: 'New Zealand' },
    { code: '+505', flag: '🇳🇮', country: 'Nicaragua' },
    { code: '+227', flag: '🇳🇪', country: 'Niger' },
    { code: '+234', flag: '🇳🇬', country: 'Nigeria' },
    { code: '+850', flag: '🇰🇵', country: 'North Korea' },
    { code: '+47', flag: '🇳🇴', country: 'Norway' },
    { code: '+968', flag: '🇴🇲', country: 'Oman' },
    { code: '+92', flag: '🇵🇰', country: 'Pakistan' },
    { code: '+970', flag: '🇵🇸', country: 'Palestine' },
    { code: '+507', flag: '🇵🇦', country: 'Panama' },
    { code: '+675', flag: '🇵🇬', country: 'Papua New Guinea' },
    { code: '+595', flag: '🇵🇾', country: 'Paraguay' },
    { code: '+51', flag: '🇵🇪', country: 'Peru' },
    { code: '+63', flag: '🇵🇭', country: 'Philippines' },
    { code: '+48', flag: '🇵🇱', country: 'Poland' },
    { code: '+351', flag: '🇵🇹', country: 'Portugal' },
    { code: '+974', flag: '🇶🇦', country: 'Qatar' },
    { code: '+40', flag: '🇷🇴', country: 'Romania' },
    { code: '+7', flag: '🇷🇺', country: 'Russia' },
    { code: '+250', flag: '🇷🇼', country: 'Rwanda' },
    { code: '+966', flag: '🇸🇦', country: 'Saudi Arabia' },
    { code: '+221', flag: '🇸🇳', country: 'Senegal' },
    { code: '+381', flag: '🇷🇸', country: 'Serbia' },
    { code: '+65', flag: '🇸🇬', country: 'Singapore' },
    { code: '+421', flag: '🇸🇰', country: 'Slovakia' },
    { code: '+386', flag: '🇸🇮', country: 'Slovenia' },
    { code: '+27', flag: '🇿🇦', country: 'South Africa' },
    { code: '+82', flag: '🇰🇷', country: 'South Korea' },
    { code: '+34', flag: '🇪🇸', country: 'Spain' },
    { code: '+94', flag: '🇱🇰', country: 'Sri Lanka' },
    { code: '+249', flag: '🇸🇩', country: 'Sudan' },
    { code: '+46', flag: '🇸🇪', country: 'Sweden' },
    { code: '+41', flag: '🇨🇭', country: 'Switzerland' },
    { code: '+963', flag: '🇸🇾', country: 'Syria' },
    { code: '+886', flag: '🇹🇼', country: 'Taiwan' },
    { code: '+992', flag: '🇹🇯', country: 'Tajikistan' },
    { code: '+255', flag: '🇹🇿', country: 'Tanzania' },
    { code: '+66', flag: '🇹🇭', country: 'Thailand' },
    { code: '+228', flag: '🇹🇬', country: 'Togo' },
    { code: '+216', flag: '🇹🇳', country: 'Tunisia' },
    { code: '+90', flag: '🇹🇷', country: 'Turkey' },
    { code: '+993', flag: '🇹🇲', country: 'Turkmenistan' },
    { code: '+256', flag: '🇺🇬', country: 'Uganda' },
    { code: '+380', flag: '🇺🇦', country: 'Ukraine' },
    { code: '+971', flag: '🇦🇪', country: 'United Arab Emirates' },
    { code: '+44', flag: '🇬🇧', country: 'United Kingdom' },
    { code: '+1', flag: '🇺🇸', country: 'United States' },
    { code: '+598', flag: '🇺🇾', country: 'Uruguay' },
    { code: '+998', flag: '🇺🇿', country: 'Uzbekistan' },
    { code: '+58', flag: '🇻🇪', country: 'Venezuela' },
    { code: '+84', flag: '🇻🇳', country: 'Vietnam' },
    { code: '+260', flag: '🇿🇲', country: 'Zambia' },
    { code: '+263', flag: '🇿🇼', country: 'Zimbabwe' },
  ];
  
  export const defaultCountryCode = '+93'; // Afghanistan